config/routes.rb
Rails.application.routes.draw do
  root 'messages#index'
  resources :messages , except: [:index, :new]

end

app/models/message.rb
class Message < ActiveRecord::Base
    # enter the name definitely
    validates :name , length: { maximum: 20 } , presence: true
    # enter the age in number definitely and the num must be 0 to 1000
    validates :age , :inclusion => { :in => 0..1000, :message => "must be between 0 and 1000" } , numericality: { only_integer: true } , presence: true
    # enter the contents definitely and the num must be 2 to 30
    validates :body , length: { minimum: 2 , maximum: 30 } , presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:edit, :update, :destroy]
  def index
    @messages = Message.all
    @message = Message.new
  end
  
  def edit
  end
  
  def update
    if @message.update(message_params)
      # if successed, redirect to top page
      redirect_to root_path , notice: 'メッセージを編集しました'
    else
      # back to the edit page when missed
      render 'edit'
    end
  end
  
  def destroy
    @message.destroy
    redirect_to root_path, notice: 'メッセージを削除しました'
  end
  
  def create
    @message = Message.new(message_params)
    if @message.save
      redirect_to root_path , notice: 'メッセージを保存しました'
    else
      # if messages can't be remembered
      @messages = Message.all
      flash.now[:alert] = "メッセージの保存に失敗しました"
      render 'index'
    end
  end
  
  private
  def message_params
    params.require(:message).permit(:name, :body, :age)
  end
  def set_message
    @message = Message.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MessageBoard</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar">
    <div class="container">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">Message Board</a>
      </div>
    </div>
  </nav>
  <div class="container">
    <% if notice %>
      <div class="alert alert-info">
        <%= notice %>
      </div>
    <% end %>
    
    <%= yield %>
  </div>
</body>
</html>

app/views/messages/_form.html.erb
<%= form_for(@message, :html => {:class => "messageForm panel panel-primary"}) do |f| %>
    <% if @message.errors.present? %>
        <div class="alert alert-danger">
            <%= alert %>
            <ul>
                <% @message.errors.full_messages.each do |full_message| %>
                <li>
                    <%= full_message %>
                </li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <div class="form">
        <div class="form-group form-inline">
            <label for="messageName">名前 :</label>
            <%= f.text_field :name , :placeholder => "name" , class: "form-control" , id: "messageName" %>
            <label for="messageAge">年齢 :</label>
            <%= f.text_field :age , :placeholder => "age" , class: "form-control" , id: "messageAge" %>
        </div>
        <div class="form-group">
            <label for="messageText">内容 :</label>
            <%= f.text_area :body , :placeholder => "body" , :maxlength => "140" , class: "form-control" , id: "messageText" %>
        </div>
        <%= f.submit class: "btn btn-sm btn-primary" %>
    </div>
<% end %>

app/views/messages/edit.html.erb
<h1>メッセージの編集</h1>

<%= render 'form' %>

app/views/messages/index.html.erb
<div class="panel panel-default messagePanel">
    <h1 class="h4">メッセージ一覧</h1>
    <% @messages.each do |message| %>
        <div class="panel-group">
            <div class="panel panel-info">
                <div class="panel-heading"><strong class="messagePanelName"><%= message.name %></strong><%= message.age %> 歳</div>
                <div class="panel-body">
                    <%= message.body %>
                    (<%= link_to "edit" , edit_message_path(message) %>
                     <%= link_to "destroy" , message , method: :delete, data: {confirm: '削除してもよろしいですか？' } %>
                    )
                </div>
            </div>
        </div>
    <% end %>
</div>

<%= render 'form' %>